export const DUMMY_EXERCISE_CATEGORIES = [
    { id: 1, name: 'Brust' },
    { id: 2, name: 'Rücken' },
    { id: 3, name: 'Beine' },
    { id: 4, name: 'Schultern' },
    { id: 5, name: 'Arme' },
    { id: 6, name: 'Core' },
];

export const DUMMY_PLAN_CATEGORIES = [
    { id: 101, name: 'Ganzkörper' },
    { id: 102, name: 'Oberkörper' },
    { id: 103, name: 'Unterkörper' },
    { id: 104, name: 'Push' },
    { id: 105, name: 'Pull' },
];

export const DUMMY_EXERCISES = [
    {
    id: 1,
    name: 'Liegestütze',
    description: 'Ausführung: Hände schulterbreit auf dem Boden platzieren, Körper in einer geraden Linie halten, Brust kontrolliert Richtung Boden senken und wieder hochdrücken. Schwierigkeit (für Muskelwachstum): Leicht: Knie-Liegestütze oder erhöhte Hände, 12–15 Wiederholungen – Fokus auf Technik und Grundbelastung der Brustmuskulatur. Mittel: Klassische Liegestütze mit Körpergewicht, 8–12 Wiederholungen – optimaler Bereich für Muskelwachstum. Schwer: Füße erhöht oder Zusatzgewicht (5–15 kg), 6–10 Wiederholungen – hohe mechanische Spannung für maximalen Muskelreiz.',
    category: 1,
    category_name: 'Brust',
    category_detail: { id: 1, name: 'Brust' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 2,
    name: 'Klimmzüge',
    description: 'Ausführung: Stange schulterbreit greifen, Körper kontrolliert hochziehen bis das Kinn über der Stange ist, anschließend langsam wieder absenken. Schwierigkeit (für Muskelwachstum): Leicht: Klimmzüge mit Widerstandsband oder negative Wiederholungen, 8–12 Wiederholungen – Grundbelastung für Rücken und Bizeps. Mittel: Klimmzüge mit eigenem Körpergewicht, 6–10 Wiederholungen – optimal für Muskelaufbau im Rücken. Schwer: Klimmzüge mit Zusatzgewicht (5–20 kg), 5–8 Wiederholungen – maximale Spannung für breiten Rücken.',
    category: 2,
    category_name: 'Rücken',
    category_detail: { id: 2, name: 'Rücken' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 3,
    name: 'Kniebeugen',
    description: 'Ausführung: Füße schulterbreit stellen, Rücken gerade halten, Hüfte nach hinten schieben und Knie beugen bis die Oberschenkel etwa parallel zum Boden sind, anschließend wieder hochdrücken. Schwierigkeit (für Muskelwachstum): Leicht: Körpergewicht oder leichtes Zusatzgewicht (5–10 kg), 12–15 Wiederholungen – Grundbelastung für Beine und Gesäß. Mittel: Zusatzgewicht 12–20 kg, 8–12 Wiederholungen – optimaler Hypertrophiebereich für Beine. Schwer: Zusatzgewicht 20–40 kg, 6–10 Wiederholungen – hohe mechanische Spannung für maximalen Muskelaufbau.',
    category: 3,
    category_name: 'Beine',
    category_detail: { id: 3, name: 'Beine' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 4,
    name: 'Plank',
    description: 'Ausführung: Unterarme auf den Boden setzen, Körper in einer geraden Linie von Kopf bis Fuß halten und Bauch sowie Gesäß anspannen. Schwierigkeit (für Muskelwachstum im Core): Leicht: 30–40 Sekunden halten – Grundspannung im Rumpf aufbauen. Mittel: 45–60 Sekunden halten – erhöhter Muskelreiz für Bauchmuskeln. Schwer: 60–90 Sekunden halten oder mit Zusatzgewicht (5–10 kg auf dem Rücken) – maximale Spannung für Core-Stabilität und Muskelwachstum.',
    category: 6,
    category_name: 'Core',
    category_detail: { id: 6, name: 'Core' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'time',
    image: null,
},
    {
        id: 5,
        name: 'Romanian Deadlifts',
        description: 'Ausführung: Hanteln vor dem Körper, Hüfte nach hinten schieben, Rücken gerade, bis knapp unter Knie senken und wieder hoch.Schwierigkeit:Leicht: 6–10 kg pro Hand, 12–15 Wiederholungen – Fokus auf Technik und saubere Bewegung.Mittel: 10–18 kg pro Hand, 10–12 Wiederholungen – gutes Gewicht für Muskelwachstum.Schwer: 18–30 kg pro Hand, 6–10 Wiederholungen – hohe Belastung für maximale Muskelspannung.',
        category: 3,
        category_name: 'Beine',
        category_detail: { id: 3, name: 'Beine' },
        public: true,
        creator: 'fitnessapp',
        tracking_type: 'reps',
        image: null,
    },
    {
    id: 6,
    name: 'Bulgarian Split Squats',
    description: 'Ausführung: Hinteren Fuß auf Stuhl oder Bank ablegen, vorderes Bein beugen bis ca. 90°, dann wieder hochdrücken. Schwierigkeit: Leicht: Körpergewicht oder 5 kg pro Hand, 12 Wiederholungen – Fokus Balance und Technik. Mittel: 8–16 kg pro Hand, 10–12 Wiederholungen – guter Muskelreiz für Beine und Gesäß. Schwer: 16–24 kg pro Hand, 6–10 Wiederholungen – intensive Belastung für Kraft und Muskelwachstum.',
    category: 3,
    category_name: 'Beine',
    category_detail: { id: 3, name: 'Beine' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 7,
    name: 'Wadenheben',
    description: 'Ausführung: Auf Zehenspitzen hochdrücken, oben kurz halten und langsam wieder absenken. Schwierigkeit: Leicht: Körpergewicht, 20 Wiederholungen – Grundbelastung der Waden. Mittel: 10–20 kg Zusatzgewicht, 15 Wiederholungen – stärkerer Muskelreiz. Schwer: 20–40 kg Zusatzgewicht, 10–12 Wiederholungen – hohe Kraftbelastung.',
    category: 3,
    category_name: 'Beine',
    category_detail: { id: 3, name: 'Beine' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 8,
    name: 'Ausfallschritte',
    description: 'Ausführung: Großen Schritt nach vorne machen, hinteres Knie Richtung Boden senken und wieder hochdrücken. Schwierigkeit: Leicht: Körpergewicht, 12 Wiederholungen pro Bein – Fokus Gleichgewicht und Technik. Mittel: 10–16 kg pro Hand, 10–12 Wiederholungen pro Bein – Muskelaufbau Beine. Schwer: 18–26 kg pro Hand, 8–10 Wiederholungen pro Bein – hohe Belastung.',
    category: 3,
    category_name: 'Beine',
    category_detail: { id: 3, name: 'Beine' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 9,
    name: 'Seitheben',
    description: 'Ausführung: Arme leicht gebeugt seitlich bis Schulterhöhe anheben und langsam absenken. Schwierigkeit: Leicht: 3–5 kg pro Hand, 15 Wiederholungen – Fokus auf Technik. Mittel: 6–8 kg pro Hand, 12 Wiederholungen – guter Muskelreiz für Schultern. Schwer: 8–12 kg pro Hand, 8–10 Wiederholungen – hohe Belastung.',
    category: 4,
    category_name: 'Schultern',
    category_detail: { id: 4, name: 'Schultern' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 10,
    name: 'Frontheben',
    description: 'Ausführung: Arme gerade nach vorne bis Schulterhöhe anheben und langsam wieder absenken. Schwierigkeit: Leicht: 3–5 kg pro Hand, 15 Wiederholungen – Fokus Kontrolle. Mittel: 6–8 kg pro Hand, 12 Wiederholungen – moderater Muskelreiz. Schwer: 8–12 kg pro Hand, 8–10 Wiederholungen – intensive Belastung der vorderen Schulter.',
    category: 4,
    category_name: 'Schultern',
    category_detail: { id: 4, name: 'Schultern' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 11,
    name: 'Reverse Flys',
    description: 'Ausführung: Oberkörper nach vorne beugen, Arme seitlich nach außen öffnen und Schulterblätter zusammenziehen. Schwierigkeit: Leicht: 3–5 kg pro Hand, 15 Wiederholungen – Fokus Technik und Haltung. Mittel: 6–8 kg pro Hand, 12 Wiederholungen – Muskelaufbau oberer Rücken. Schwer: 8–10 kg pro Hand, 10 Wiederholungen – hohe Spannung auf hintere Schulter.',
    category: 4,
    category_name: 'Schultern',
    category_detail: { id: 4, name: 'Schultern' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 12,
    name: 'Schulterdrücken',
    description: 'Ausführung: Hanteln auf Schulterhöhe starten und über den Kopf nach oben drücken. Schwierigkeit: Leicht: 6–10 kg pro Hand, 12 Wiederholungen – Technik und Stabilität. Mittel: 10–18 kg pro Hand, 10 Wiederholungen – Muskelaufbau Schultern. Schwer: 18–26 kg pro Hand, 6–8 Wiederholungen – maximale Kraftbelastung.',
    category: 4,
    category_name: 'Schultern',
    category_detail: { id: 4, name: 'Schultern' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 13,
    name: 'Bizeps Curls',
    description: 'Ausführung: Arme eng am Körper halten und Hanteln kontrolliert nach oben ziehen. Schwierigkeit: Leicht: 6–8 kg pro Hand, 15 Wiederholungen – Fokus Technik. Mittel: 10–14 kg pro Hand, 10–12 Wiederholungen – Muskelaufbau Bizeps. Schwer: 16–22 kg pro Hand, 6–10 Wiederholungen – maximale Muskelspannung.',
    category: 5,
    category_name: 'Arme',
    category_detail: { id: 5, name: 'Arme' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 14,
    name: 'Crunches',
    description: 'Ausführung: Schultern leicht vom Boden anheben und Bauch anspannen. Schwierigkeit: Leicht: Körpergewicht, 20 Wiederholungen – Grundübung Bauch. Mittel: 5–10 kg Zusatzgewicht, 15 Wiederholungen – stärkerer Muskelreiz. Schwer: 10–15 kg Zusatzgewicht, 12 Wiederholungen – intensive Belastung.',
    category: 6,
    category_name: 'Core',
    category_detail: { id: 6, name: 'Core' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 15,
    name: 'Seitliche Crunches',
    description: 'Ausführung: Oberkörper diagonal zur Seite drehen und Bauch anspannen. Schwierigkeit: Leicht: Körpergewicht, 20 Wiederholungen pro Seite – Technik lernen. Mittel: 5 kg Zusatzgewicht, 15 Wiederholungen pro Seite – stärkerer Reiz für schräge Bauchmuskeln. Schwer: 8–10 kg Zusatzgewicht, 12 Wiederholungen pro Seite – hohe Spannung.',
    category: 6,
    category_name: 'Core',
    category_detail: { id: 6, name: 'Core' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
},
{
    id: 16,
    name: 'Sit Ups',
    description: 'Ausführung: Komplett aufsetzen und kontrolliert wieder zurückrollen. Schwierigkeit: Leicht: Körpergewicht, 15 Wiederholungen – Grundübung Bauch. Mittel: 5–10 kg Zusatzgewicht, 12 Wiederholungen – Muskelaufbau Bauch. Schwer: 10–15 kg Zusatzgewicht, 10 Wiederholungen – hohe Belastung.',
    category: 6,
    category_name: 'Core',
    category_detail: { id: 6, name: 'Core' },
    public: true,
    creator: 'fitnessapp',
    tracking_type: 'reps',
    image: null,
}
];

export const DUMMY_TRAINING_PLANS = [
    {
        id: 1,
        name: 'Ganzkörper Workout',
        description: 'Ein perfekter Einstieg für Gäste, um alle Muskelgruppen zu trainieren.',
        category: 101,
        category_detail: DUMMY_PLAN_CATEGORIES.find(c => c.id === 101),
        creator_name: 'fitnessapp',
        order: [1, 3, 2, 4],
        exercises: [DUMMY_EXERCISES[0], DUMMY_EXERCISES[2], DUMMY_EXERCISES[1], DUMMY_EXERCISES[3]]
    }
];

export const DUMMY_RECOMMENDATIONS = {
    plans: [DUMMY_TRAINING_PLANS[0]],
    exercises: [DUMMY_EXERCISES[0]]
};
